### PR TITLE
Change from Pleco to Tanton

### PR DESCRIPTION
**Pull request by chase-manning**
Pleco is no longer maintained, it has outstanding issues and hasn't had a new contribution in two and half years.  

[Tanton](https://github.com/chase-manning/tanton) is a fork of Pleco that is backward compatable and actively maintained.  

This PR changes from using Pleco to using Tanton.

### CODE REVIEW

**Comment by chase-manning** [comment]
@dmvict @Wandalen PR for review when you have a moment 😄

**Comment by dmvict** [comment]
Hello, @chase-manning 

The PR looks good. 

I will merge it after fixing bugs in #283. The scheme: 
- I will merge #283 when the bugs fixing well done
- you will merge the changes 
- I will see the workflow run results and merge PR if it is OK.

**Comment by chase-manning** [comment]
@dmvict Sounds great! Will do 😄

**Comment by dmvict** [comment]
> @dmvict Sounds great! Will do smile

Hello. 

@chase-manning Could you please merge the branch `alpha` of the repo in this branch? After that, I will merge the PR.

**Comment by chase-manning** [comment]
Pleco is now under active maintenance again, and the improvements from Tanton have been merged back into Pleco 😄 

So we can close this PR now, sorry about wasting your time here!

**Comment by dmvict** [comment]
@chase-manning Thank you for the PR. It is important to have maintained dependencies :)

**Pull request closed without merging**
